// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using seminario.Infrastructure.Persistence;

#nullable disable

namespace seminario.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DataProtected")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsX509Certificate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Use")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Use");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("ConsumedTime");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("seminario.Domain.Entities.AdminBodega", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("BodegaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "BodegaId");

                    b.HasIndex("BodegaId")
                        .IsUnique();

                    b.ToTable("AdminBodega");
                });

            modelBuilder.Entity("seminario.Domain.Entities.AdminEmpresa", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "EmpresaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("AdminEmpresa");
                });

            modelBuilder.Entity("seminario.Domain.Entities.AdminPlanta", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PlantaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "PlantaId");

                    b.HasIndex("PlantaId")
                        .IsUnique();

                    b.ToTable("AdminPlanta");
                });

            modelBuilder.Entity("seminario.Domain.Entities.AlgoritmoMinimizacion", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AlgoritmoMinimizacion");
                });

            modelBuilder.Entity("seminario.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("seminario.Domain.Entities.BitacoraEstadoMovimientoBodega", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EstadoMovimientoBodegaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MovimientoBodegaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EstadoMovimientoBodegaId");

                    b.HasIndex("MovimientoBodegaId", "EstadoMovimientoBodegaId");

                    b.ToTable("BitacoraEstadoMovimientoBodega");
                });

            modelBuilder.Entity("seminario.Domain.Entities.BitacoraEstadoPedidoMaterial", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EstadoPedidoMaterialId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PedidoMaterialId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EstadoPedidoMaterialId");

                    b.HasIndex("PedidoMaterialId", "EstadoPedidoMaterialId");

                    b.ToTable("BitacoraEstadoPedidoMaterial");
                });

            modelBuilder.Entity("seminario.Domain.Entities.BitacoraEstadoSolicitudTransporteCarga", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EstadoSolicitudTransporteCargaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SolicitudTransporteCargaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EstadoSolicitudTransporteCargaId");

                    b.HasIndex("SolicitudTransporteCargaId", "EstadoSolicitudTransporteCargaId");

                    b.ToTable("BitacoraEstadoSolicitudTransporteCarga");
                });

            modelBuilder.Entity("seminario.Domain.Entities.BitacoraEstadoTransporteCarga", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DetalleTransporteCargaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("EstadoTransporteCargaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EstadoTransporteCargaId");

                    b.HasIndex("DetalleTransporteCargaId", "EstadoTransporteCargaId");

                    b.ToTable("BitacoraEstadoTransporteCarga");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Bodega", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoBodega")
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Bodega");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Conductor", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoLicencia")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NoLicencia");

                    b.HasIndex("UserId");

                    b.ToTable("Conductor");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Departamento", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PaisId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion");

                    b.HasIndex("PaisId");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("seminario.Domain.Entities.DetalleTransporteCarga", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ConductorId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("EstadoTransporteCargaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFinProgramado")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaIniciado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInicioProgramado")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaTerminado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RutaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SolicitudTransporteCargaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.Property<int?>("VehiculoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.HasIndex("EstadoTransporteCargaId");

                    b.HasIndex("RutaId");

                    b.HasIndex("SolicitudTransporteCargaId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("DetalleTransporteCarga");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Empresa", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nit")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int?>("TipoEmpresaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TipoEmpresaId");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("seminario.Domain.Entities.EstadoMovimientoBodega", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EstadoMovimientoBodega");
                });

            modelBuilder.Entity("seminario.Domain.Entities.EstadoPedidoMaterial", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EstadoPedidoMaterial");
                });

            modelBuilder.Entity("seminario.Domain.Entities.EstadoSolicitudTransporteCarga", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EstadoSolicitudTransporteCarga");
                });

            modelBuilder.Entity("seminario.Domain.Entities.EstadoTransporteCarga", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EstadoTransporteCarga");
                });

            modelBuilder.Entity("seminario.Domain.Entities.IngresoMaterial", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BodegaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double?>("Cantidad")
                        .HasColumnType("double");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MaterialId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ProveedorMaterialId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BodegaId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProveedorMaterialId");

                    b.ToTable("IngresoMaterial");
                });

            modelBuilder.Entity("seminario.Domain.Entities.InventarioBodega", b =>
                {
                    b.Property<int?>("BodegaId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<double?>("CantidadDisponible")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValue(0.0);

                    b.Property<double?>("CantidadReservada")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("BodegaId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("InventarioBodega");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Material", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Peso")
                        .HasColumnType("double");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int?>("TipoMaterialId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("UnidadMedidaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TipoMaterialId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("seminario.Domain.Entities.MovimientoBodega", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BodegaDestinoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("BodegaOrigenId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double?>("Cantidad")
                        .IsRequired()
                        .HasColumnType("double");

                    b.Property<int?>("ConductorId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int?>("EstadoMovimientoBodegaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCargado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaDescargado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInicioProgramado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PedidoMaterialId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.Property<int?>("VehiculoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BodegaDestinoId");

                    b.HasIndex("BodegaOrigenId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("EstadoMovimientoBodegaId");

                    b.HasIndex("PedidoMaterialId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("MovimientoBodega");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Municipio", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("DepartamentoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Descripcion");

                    b.ToTable("Municipio");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Pais", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("seminario.Domain.Entities.PedidoMaterial", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BodegaSolicitaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double?>("Cantidad")
                        .IsRequired()
                        .HasColumnType("double");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int?>("EstadoPedidoMaterialId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAprobado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaSolicitado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MaterialId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BodegaSolicitaId");

                    b.HasIndex("EstadoPedidoMaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("PedidoMaterial");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Planta", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BodegaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int?>("TipoPlantaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BodegaId");

                    b.HasIndex("TipoPlantaId");

                    b.ToTable("Planta");
                });

            modelBuilder.Entity("seminario.Domain.Entities.ProveedorMaterial", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProveedorMaterial");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Ruta", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("CostoPorCarga")
                        .HasColumnType("decimal(65,30)");

                    b.Property<double?>("Distancia")
                        .HasColumnType("double");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int?>("Tiempo")
                        .HasColumnType("int");

                    b.Property<int?>("TipoRutaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionDestinoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionOrigenId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TipoRutaId");

                    b.HasIndex("UbicacionDestinoId");

                    b.HasIndex("UbicacionOrigenId");

                    b.ToTable("Ruta");
                });

            modelBuilder.Entity("seminario.Domain.Entities.SolicitudTransporteCarga", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AlgoritmoMinimizacionId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("EmpresaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("EstadoSolicitudTransporteCargaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAprobado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInicioSolicitado")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("PesoCarga")
                        .IsRequired()
                        .HasColumnType("double");

                    b.Property<int?>("TiempoEstimado")
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionDestinoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionOrigenId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlgoritmoMinimizacionId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EstadoSolicitudTransporteCargaId");

                    b.HasIndex("UbicacionDestinoId");

                    b.HasIndex("UbicacionOrigenId");

                    b.ToTable("SolicitudTransporteCarga");
                });

            modelBuilder.Entity("seminario.Domain.Entities.TipoEmpresa", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TipoEmpresa");
                });

            modelBuilder.Entity("seminario.Domain.Entities.TipoMaterial", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TipoMaterial");
                });

            modelBuilder.Entity("seminario.Domain.Entities.TipoPlanta", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TipoPlanta");
                });

            modelBuilder.Entity("seminario.Domain.Entities.TipoRuta", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TipoRuta");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Ubicacion", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double");

                    b.Property<int?>("MunicipioId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoUbicacion")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Ubicacion");
                });

            modelBuilder.Entity("seminario.Domain.Entities.UbicacionEmpresa", b =>
                {
                    b.Property<int?>("UbicacionId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("UbicacionId", "EmpresaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("UbicacionEmpresa");
                });

            modelBuilder.Entity("seminario.Domain.Entities.UnidadMedida", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("DescripcionCorta")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("DescripcionPlural")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UnidadMedida");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double?>("CapacidadCarga")
                        .IsRequired()
                        .HasColumnType("double");

                    b.Property<string>("Codigo")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<bool?>("EsUsoInterno")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Placa")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("seminario.Domain.Entities.VehiculoConductor", b =>
                {
                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int");

                    b.Property<int?>("ConductorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsert")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("longtext");

                    b.HasKey("VehiculoId", "ConductorId");

                    b.HasIndex("ConductorId");

                    b.ToTable("VehiculoConductor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("seminario.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("seminario.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("seminario.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("seminario.Domain.Entities.AdminBodega", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Bodega", "Bodega")
                        .WithOne("AdminBodega")
                        .HasForeignKey("seminario.Domain.Entities.AdminBodega", "BodegaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("User");
                });

            modelBuilder.Entity("seminario.Domain.Entities.AdminEmpresa", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("User");
                });

            modelBuilder.Entity("seminario.Domain.Entities.AdminPlanta", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Planta", "Planta")
                        .WithOne("AdminPlanta")
                        .HasForeignKey("seminario.Domain.Entities.AdminPlanta", "PlantaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Planta");

                    b.Navigation("User");
                });

            modelBuilder.Entity("seminario.Domain.Entities.BitacoraEstadoMovimientoBodega", b =>
                {
                    b.HasOne("seminario.Domain.Entities.EstadoMovimientoBodega", "EstadoMovimientoBodega")
                        .WithMany()
                        .HasForeignKey("EstadoMovimientoBodegaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.MovimientoBodega", "MovimientoBodega")
                        .WithMany()
                        .HasForeignKey("MovimientoBodegaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoMovimientoBodega");

                    b.Navigation("MovimientoBodega");
                });

            modelBuilder.Entity("seminario.Domain.Entities.BitacoraEstadoPedidoMaterial", b =>
                {
                    b.HasOne("seminario.Domain.Entities.EstadoPedidoMaterial", "EstadoPedidoMaterial")
                        .WithMany()
                        .HasForeignKey("EstadoPedidoMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.PedidoMaterial", "PedidoMaterial")
                        .WithMany()
                        .HasForeignKey("PedidoMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoPedidoMaterial");

                    b.Navigation("PedidoMaterial");
                });

            modelBuilder.Entity("seminario.Domain.Entities.BitacoraEstadoSolicitudTransporteCarga", b =>
                {
                    b.HasOne("seminario.Domain.Entities.EstadoSolicitudTransporteCarga", "EstadoSolicitudTransporteCarga")
                        .WithMany()
                        .HasForeignKey("EstadoSolicitudTransporteCargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.SolicitudTransporteCarga", "SolicitudTransporteCarga")
                        .WithMany()
                        .HasForeignKey("SolicitudTransporteCargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoSolicitudTransporteCarga");

                    b.Navigation("SolicitudTransporteCarga");
                });

            modelBuilder.Entity("seminario.Domain.Entities.BitacoraEstadoTransporteCarga", b =>
                {
                    b.HasOne("seminario.Domain.Entities.DetalleTransporteCarga", "DetalleTransporteCarga")
                        .WithMany()
                        .HasForeignKey("DetalleTransporteCargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.EstadoTransporteCarga", "EstadoTransporteCarga")
                        .WithMany()
                        .HasForeignKey("EstadoTransporteCargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetalleTransporteCarga");

                    b.Navigation("EstadoTransporteCarga");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Bodega", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Conductor", b =>
                {
                    b.HasOne("seminario.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Departamento", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("seminario.Domain.Entities.DetalleTransporteCarga", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.EstadoTransporteCarga", "EstadoTransporteCarga")
                        .WithMany()
                        .HasForeignKey("EstadoTransporteCargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Ruta", "Ruta")
                        .WithMany()
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.SolicitudTransporteCarga", "SolicitudTransporteCarga")
                        .WithMany()
                        .HasForeignKey("SolicitudTransporteCargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("EstadoTransporteCarga");

                    b.Navigation("Ruta");

                    b.Navigation("SolicitudTransporteCarga");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Empresa", b =>
                {
                    b.HasOne("seminario.Domain.Entities.TipoEmpresa", "TipoEmpresa")
                        .WithMany()
                        .HasForeignKey("TipoEmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoEmpresa");
                });

            modelBuilder.Entity("seminario.Domain.Entities.IngresoMaterial", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Bodega", "Bodega")
                        .WithMany()
                        .HasForeignKey("BodegaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.ProveedorMaterial", "ProveedorMaterial")
                        .WithMany()
                        .HasForeignKey("ProveedorMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("Material");

                    b.Navigation("ProveedorMaterial");
                });

            modelBuilder.Entity("seminario.Domain.Entities.InventarioBodega", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Bodega", "Bodega")
                        .WithMany()
                        .HasForeignKey("BodegaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Material", b =>
                {
                    b.HasOne("seminario.Domain.Entities.TipoMaterial", "TipoMaterial")
                        .WithMany()
                        .HasForeignKey("TipoMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoMaterial");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("seminario.Domain.Entities.MovimientoBodega", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Bodega", "BodegaDestino")
                        .WithMany()
                        .HasForeignKey("BodegaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Bodega", "BodegaOrigen")
                        .WithMany()
                        .HasForeignKey("BodegaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.EstadoMovimientoBodega", "EstadoMovimientoBodega")
                        .WithMany()
                        .HasForeignKey("EstadoMovimientoBodegaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.PedidoMaterial", "PedidoMaterial")
                        .WithMany()
                        .HasForeignKey("PedidoMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BodegaDestino");

                    b.Navigation("BodegaOrigen");

                    b.Navigation("Conductor");

                    b.Navigation("EstadoMovimientoBodega");

                    b.Navigation("PedidoMaterial");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("seminario.Domain.Entities.PedidoMaterial", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Bodega", "BodegaSolicita")
                        .WithMany()
                        .HasForeignKey("BodegaSolicitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.EstadoPedidoMaterial", "EstadoPedidoMaterial")
                        .WithMany()
                        .HasForeignKey("EstadoPedidoMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BodegaSolicita");

                    b.Navigation("EstadoPedidoMaterial");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Planta", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Bodega", "Bodega")
                        .WithMany()
                        .HasForeignKey("BodegaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.TipoPlanta", "TipoPlanta")
                        .WithMany()
                        .HasForeignKey("TipoPlantaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("TipoPlanta");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Ruta", b =>
                {
                    b.HasOne("seminario.Domain.Entities.TipoRuta", "TipoRuta")
                        .WithMany()
                        .HasForeignKey("TipoRutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Ubicacion", "UbicacionDestino")
                        .WithMany()
                        .HasForeignKey("UbicacionDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Ubicacion", "UbicacionOrigen")
                        .WithMany()
                        .HasForeignKey("UbicacionOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoRuta");

                    b.Navigation("UbicacionDestino");

                    b.Navigation("UbicacionOrigen");
                });

            modelBuilder.Entity("seminario.Domain.Entities.SolicitudTransporteCarga", b =>
                {
                    b.HasOne("seminario.Domain.Entities.AlgoritmoMinimizacion", "AlgoritmoMinimizacion")
                        .WithMany()
                        .HasForeignKey("AlgoritmoMinimizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.EstadoSolicitudTransporteCarga", "EstadoSolicitudTransporteCarga")
                        .WithMany()
                        .HasForeignKey("EstadoSolicitudTransporteCargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Ubicacion", "UbicacionDestino")
                        .WithMany()
                        .HasForeignKey("UbicacionDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Ubicacion", "UbicacionOrigen")
                        .WithMany()
                        .HasForeignKey("UbicacionOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlgoritmoMinimizacion");

                    b.Navigation("Empresa");

                    b.Navigation("EstadoSolicitudTransporteCarga");

                    b.Navigation("UbicacionDestino");

                    b.Navigation("UbicacionOrigen");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Ubicacion", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("seminario.Domain.Entities.UbicacionEmpresa", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("seminario.Domain.Entities.VehiculoConductor", b =>
                {
                    b.HasOne("seminario.Domain.Entities.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seminario.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("seminario.Domain.Entities.Bodega", b =>
                {
                    b.Navigation("AdminBodega")
                        .IsRequired();
                });

            modelBuilder.Entity("seminario.Domain.Entities.Planta", b =>
                {
                    b.Navigation("AdminPlanta")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
